#!/usr/bin/python
import pygame, sys
from pygame.locals import *

pygame.mixer.init()
soundObj = pygame.mixer.Sound('beeps.wav')
soundObj.play()
import time
time.sleep(1) # wait and let the sound play for 1 second
soundObj.stop()
